version: '2'
services:
    web:
        image: 'django-asgi'
        restart: 'no'
        ports:
            - '8081:8081'
        network_mode: "host"
        volumes:
            - './srv:/spotinder'
            - './nginx/nginx.conf:/etc/nginx/nginx.conf'
